name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca8a77faeecd0033896316917d9ab4ae3fd1ce8b1c4009b61cf8cc57335a660e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
