name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c1e29828f240e29c0571c6b40df2d27fa723ab4bd22c05ac66aa26571c8a317"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
