name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e92b789bec9ee5104b0872f666b5fa7547aa99d4de0a58dc86dc972cea60eb"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
