name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30c9d1bb867f2fbcd2fe563e4f63e5b83e9f47f1384ff69d4d73efa75740370f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
