name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0afd61fd2e27e6d09c2661501def2280d40a2c4b17c724cb5f874ee79bc9c55"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
