name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "013a0c3a93b2da695e0482e7c273c2ce4e83b8d34e09130400115e8865bd467d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
