name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88e5f072a6f795aba839c72292dfa09af340091a6d8405b76b899d6a9e9931f6"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
