name = "Projet Equation"
author = "Outra256, Gocraft, Ehrmantraut_, GeoffreyGx"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f791f3b4e8bff1769ce8f536cf35bf87213f713c9c3c052eaa59ef55a2de26a"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
