name = "Celestium SMP"
author = "GeoffreyGx"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e25889af4928b5992ec51dcbc8bc086c86378d2426294d27f609b9ba6f30e2c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
